[package]
name = "otterc_utils"
version = "0.1.0"
edition = "2024"

[dependencies]
ariadne = "0.3"
tracing-subscriber = { version = "0.3", features = ["fmt", "env-filter"] }
otterc_span.path = "../otterc_span"

[lints]
workspace = true
