[package]
name = "otterc_module"
version = "0.1.0"
edition = "2024"

[dependencies]
otterc_ast.path = "../otterc_ast"
otterc_lexer.path = "../otterc_lexer"
otterc_parser.path = "../otterc_parser"

anyhow = "1.0"
tempfile = "3.10"

[lints]
workspace = true
