[package]
name = "otterc_lexer"
version = "0.1.0"
edition = "2024"

[dependencies]
thiserror = "1.0"

otterc_span.path = "../otterc_span"
otterc_utils.path = "../otterc_utils"

[lints]
workspace = true
